spring: 
   profiles: dev
   application: 
      name: woniucloud-provider-dev  

spring: 
   profiles: test
   application: 
      name: woniucloud-provider-test
 
spring: 
   profiles: pre
   application: 
      name: woniucloud-provider-pre
